[theme]
base = "light"
backgroundColor = "white"
secondaryBackgroundColor = "#ebffef8c"
textColor = "black"
font = "inter"
codeBackgroundColor = "white"
primaryColor = "#00CC2D"
buttonRadius = "0.3rem"  # z. B. eckiger statt "full"

[theme.sidebar]
backgroundColor = "#F2F2F2"

