[theme]
base = "light"
backgroundColor = "white"
secondaryBackgroundColor = "#ebffef8c"
textColor = "black"
font = "inter"
codeBackgroundColor = "white"
primaryColor = "#00CC2D"

[theme.sidebar]
backgroundColor = "#F2F2F2"

